version: "3.9"

services:
  iis:
    image: mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019
    container_name: iis_webapp
    ports:
      - "8080:80"  # Konteynerin 80 portunu yerel 8080 portuna yönlendiriyoruz
    volumes:
      - ${PWD}/app:/inetpub/wwwroot  # Web uygulamanızın dosyalarını bu klasöre bağlayın
    networks:
      - app-network
    environment:
      - COMPLUS_EnableDiagnostics=0 # Performans için önerilir, gerekliyse devre dışı bırakabilirsiniz
    tty: true  # IIS konteynerinde hata ayıklama için önerilir

networks:
  app-network:
    driver: nat  # Windows konteynerları için 'nat' ağ sürücüsü önerilir
